export default [
  {
    cell_id: 'C07',
    state_id: 'SC',
    middle_cell_id: 'C07',
    company_name: '43 SA',
    email_associative_contribution: '.',
    short_name: '43 SA',
    editable: 'true',
    email_ccee_information: '',
    cell_name: 'CELULA FLN01',
    email_invoice: '.',
    middle_name: 'Julia Burigo de Carvalho',
    front_name: 'Everton Henrique Matsumoto',
    cnpj: '82641606000170',
    middle_id: '000276',
    email_seasonalization: '',
    front_id: '000400',
    economicgroup_name: '43 SA',
    id: '00185601'
  },
  {
    cell_id: 'C07',
    state_id: 'SC',
    middle_cell_id: 'C07',
    company_name: 'ABBASPEL',
    email_associative_contribution: '.',
    short_name: 'ABBASPEL',
    editable: 'true',
    email_ccee_information: '',
    cell_name: 'CELULA FLN01',
    email_invoice: '.',
    middle_name: 'Julia Burigo de Carvalho',
    front_name: 'Lorenzo Valsangiacomo',
    cnpj: '04490046000197',
    middle_id: '000276',
    email_seasonalization: '',
    front_id: '000255',
    economicgroup_name: 'ABBASPEL',
    id: '03327501'
  },
  {
    cell_id: 'C07',
    state_id: 'SC',
    middle_cell_id: 'C07',
    company_name: 'ABIMAR SUPERMERCADOS - EM',
    email_associative_contribution: '.',
    short_name: 'ABIMAR SUPERMERCADOS',
    editable: 'true',
    email_ccee_information: '',
    cell_name: 'CELULA FLN01',
    email_invoice: '.',
    middle_name: 'Julia Burigo de Carvalho',
    front_name: 'Sergio Luiz Scramin Junior',
    cnpj: '00508070000406',
    middle_id: '000276',
    email_seasonalization: '',
    front_id: '000401',
    economicgroup_name: 'ABIMAR SUPERMERCADOS - GE',
    id: '08082401'
  },
  {
    cell_id: 'C07',
    state_id: 'SC',
    middle_cell_id: 'C07',
    company_name: 'ACOPECAS',
    email_associative_contribution: '.',
    short_name: 'ACOPECAS',
    editable: 'true',
    email_ccee_information: '',
    cell_name: 'CELULA FLN01',
    email_invoice: '.',
    middle_name: 'Rodrigo Lopes Fernandes',
    front_name: 'Everton Henrique Matsumoto',
    cnpj: '75883975000104',
    middle_id: '000514',
    email_seasonalization: '',
    front_id: '000400',
    economicgroup_name: 'ACOPECAS',
    id: '00110001'
  },
  {
    cell_id: 'C07',
    state_id: 'SC',
    middle_cell_id: 'C07',
    company_name: 'AIRELA INDUSTRIA FARMACEUTICA LTDA - EM',
    email_associative_contribution: '.',
    short_name: 'AIRELA',
    editable: 'true',
    email_ccee_information: '',
    cell_name: 'CELULA FLN01',
    email_invoice: '.',
    middle_name: 'Julia Burigo de Carvalho',
    front_name: 'Everton Henrique Matsumoto',
    cnpj: '01858973000129',
    middle_id: '000276',
    email_seasonalization: '',
    front_id: '000400',
    economicgroup_name: 'AIRELA INDUSTRIA FARMACEUTICA LTDA - GE',
    id: '08094201'
  },
  {
    cell_id: 'C07',
    state_id: 'SC',
    middle_cell_id: 'C07',
    company_name: 'ALTENBURG',
    email_associative_contribution: '.',
    short_name: 'ALTENBURG I',
    editable: 'true',
    email_ccee_information: '',
    cell_name: 'CELULA FLN01',
    email_invoice: '.',
    middle_name: 'Julia Burigo de Carvalho',
    front_name: 'Everton Henrique Matsumoto',
    cnpj: '75293662000104',
    middle_id: '000276',
    email_seasonalization: '',
    front_id: '000400',
    economicgroup_name: 'ALTENBURG',
    id: '00218301'
  },
  {
    cell_id: 'C07',
    state_id: 'SC',
    middle_cell_id: 'C07',
    company_name: 'ALTENBURG',
    email_associative_contribution: '.',
    short_name: 'ALTENBURG II',
    editable: 'true',
    email_ccee_information: '',
    cell_name: 'CELULA FLN01',
    email_invoice: '.',
    middle_name: 'Julia Burigo de Carvalho',
    front_name: 'Everton Henrique Matsumoto',
    cnpj: '75293662000449',
    middle_id: '000276',
    email_seasonalization: '',
    front_id: '000400',
    economicgroup_name: 'ALTENBURG',
    id: '00218302'
  },
  {
    cell_id: 'C07',
    state_id: 'SC',
    middle_cell_id: 'C07',
    company_name: 'ARTEPINUS',
    email_associative_contribution: '.',
    short_name: 'ARTEPINUS',
    editable: 'true',
    email_ccee_information: '',
    cell_name: 'CELULA FLN01',
    email_invoice: '.',
    middle_name: 'Emile Dall Orsoletta',
    front_name: 'Sergio Luiz Scramin Junior',
    cnpj: '76848506000117',
    middle_id: '000126',
    email_seasonalization: '',
    front_id: '000401',
    economicgroup_name: 'ARTEPINUS',
    id: '01126301'
  },
  {
    cell_id: 'C07',
    state_id: 'SC',
    middle_cell_id: 'C07',
    company_name: 'HOSPITAL MAICE - EM',
    email_associative_contribution: '.',
    short_name: 'HOSPITAL MAICE',
    editable: 'true',
    email_ccee_information: '',
    cell_name: 'CELULA FLN01',
    email_invoice: '.',
    middle_name: 'Emile Dall Orsoletta',
    front_name: 'Lorenzo Valsangiacomo',
    cnpj: '33543356002093',
    middle_id: '000126',
    email_seasonalization: '',
    front_id: '000255',
    economicgroup_name: 'ASSOCIACAO FRANCO BRASILEIRA - HOSPITAL',
    id: '08783401'
  },
  {
    cell_id: 'C07',
    state_id: 'SC',
    middle_cell_id: 'C07',
    company_name: 'BOTUVERA IND. COM. ACUM. COMP. LTDA EPP',
    email_associative_contribution: '.',
    short_name: 'ERBS INDUSTRIA',
    editable: 'true',
    email_ccee_information: '',
    cell_name: 'CELULA FLN01',
    email_invoice: '.',
    middle_name: 'Rodrigo Lopes Fernandes',
    front_name: 'Lorenzo Valsangiacomo',
    cnpj: '05730180000180',
    middle_id: '000514',
    email_seasonalization: '',
    front_id: '000255',
    economicgroup_name: 'BATERIAS ERBS',
    id: '00184301'
  }
]
